export const QUERY_KEYS = {
  userOne: 'userOne',
  createList: 'createList',
  uploadImage: 'uploadImage',
  getAllList: 'getAllList',
  getListDetail: 'getListDetail',
  getCategories: 'getCategories',
  getComments: 'getComments',
  getRecommendedLists: 'getRecommendedLists',
  getRecommendedUsers: 'getRecommendedUsers',
  getTrendingLists: 'getTrendingLists',
  follow: 'follow',
  deleteFollow: 'deleteFollow',
  deleteFollower: 'deleteFollower',
  getFollowingList: 'getFollowingList',
  getFollowerList: 'getFollowerList',
  getUsersByNicknameSearch: 'getUsersByNicknameSearch',
  notifications: 'notifications',
};
