import { TopicType } from '@/lib/types/topicType';

export const topicsData: TopicType[] = [
  {
    categoryEngName: '음악',
    categoryKorName: '음악',
    title: 'AI와 머신러닝의 미래',
    description: 'AI와 머신러닝이 앞으로 어떻게 발전할지에 대한 토론',
    ownerId: 101,
    ownerNickname: 'TechGuru',
    isAnonymous: false,
  },
  {
    categoryEngName: '장소',
    categoryKorName: '장소',
    title: '헬스케어의 혁신',
    description: '첨단 기술을 활용한 헬스케어 서비스의 혁신과 미래',
    ownerId: 102,
    ownerNickname: 'HealthExpert',
    isAnonymous: true,
  },
  {
    categoryEngName: '일상생활',
    categoryKorName: '일상생활',
    title: '비즈니스 전략 세우기',
    description: '효과적인 비즈니스 전략을 세우는 방법에 대해 논의합니다.',
    ownerId: 103,
    ownerNickname: 'BusinessMind',
    isAnonymous: false,
  },
  {
    categoryEngName: '전체',
    categoryKorName: '전체',
    title: '온라인 교육의 장점',
    description: '온라인 교육 플랫폼의 장점과 한계에 대해 토론',
    ownerId: 104,
    ownerNickname: 'EduMaster',
    isAnonymous: true,
  },
  {
    categoryEngName: '도서',
    categoryKorName: '도서',
    title: '미래의 게임 기술',
    description: '가상 현실과 증강 현실을 활용한 차세대 게임 기술',
    ownerId: 105,
    ownerNickname: 'GameChanger',
    isAnonymous: false,
  },
  {
    categoryEngName: '장소',
    categoryKorName: '장소',
    title: '우주 탐사 기술의 발전',
    description: '최근 우주 탐사 기술의 혁신과 가능성에 대해 논의',
    ownerId: 106,
    ownerNickname: 'SpaceExplorer',
    isAnonymous: true,
  },
  {
    categoryEngName: '도서',
    categoryKorName: '도서',
    title: '스포츠와 데이터 분석',
    description: '데이터 분석을 통해 스포츠 경기의 결과를 예측하는 방법',
    ownerId: 107,
    ownerNickname: 'DataSports',
    isAnonymous: false,
  },
  {
    categoryEngName: '장소',
    categoryKorName: '장소',
    title: '정치와 소셜 미디어',
    description: '소셜 미디어가 현대 정치에 미치는 영향에 대해 토론',
    ownerId: 108,
    ownerNickname: 'PoliticalVoice',
    isAnonymous: true,
  },
  {
    categoryEngName: '음식',
    categoryKorName: '음식',
    title: '정치와 소셜 미디어',
    description: '소셜 미디어가 현대 정치에 미치는 영향에 대해 토론',
    ownerId: 108,
    ownerNickname: 'PoliticalVoice',
    isAnonymous: true,
  },
  {
    categoryEngName: '기타',
    categoryKorName: '기타',
    title: '정치와 소셜 미디어',
    description: '소셜 미디어가 현대 정치에 미치는 영향에 대해 토론',
    ownerId: 108,
    ownerNickname: 'PoliticalVoice',
    isAnonymous: true,
  },
  {
    categoryEngName: '일상생활',
    categoryKorName: '일상생활',
    title: '정치와 소셜 미디어',
    description: '소셜 미디어가 현대 정치에 미치는 영향에 대해 토론',
    ownerId: 108,
    ownerNickname: 'PoliticalVoice',
    isAnonymous: true,
  },
  {
    categoryEngName: '일상생활',
    categoryKorName: '일상생활',
    title: '정치와 소셜 미디어',
    description: '소셜 미디어가 현대 정치에 미치는 영향에 대해 토론',
    ownerId: 108,
    ownerNickname: 'PoliticalVoice',
    isAnonymous: true,
  },
  {
    categoryEngName: '일상생활',
    categoryKorName: '일상생활',
    title: '정치와 소셜 미디어',
    description: '소셜 미디어가 현대 정치에 미치는 영향에 대해 토론',
    ownerId: 108,
    ownerNickname: 'PoliticalVoice',
    isAnonymous: true,
  },
  {
    categoryEngName: '일상생활',
    categoryKorName: '일상생활',
    title: '정치와 소셜 미디어',
    description: '소셜 미디어가 현대 정치에 미치는 영향에 대해 토론',
    ownerId: 108,
    ownerNickname: 'PoliticalVoice',
    isAnonymous: true,
  },
];
